### ISSUE TITLE
supported php version?

### ISSUE THREAD

**Issue by codinglist** [chopins/php-libui#5]
## environment
os:macos13.5.1(intel) 
php -v
PHP 8.1.27 (cli) (built: Dec 19 2023 20:35:55) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.27, Copyright (c), by Zend Technologies
(base)

## install
```
composer require toknot/php-libui -vvv
```

## error:
 [InvalidArgumentException]
  Could not find a version of package toknot/php-libui matching your minimum-stability (stable). Requi
  re it with an explicit version constraint allowing its desired stability.

**Comment by chopins** [comment]
use dev version, no stable version
`composer require toknot/php-libui=master-dev`
